apiVersion: v1
kind: Service
metadata:
  name: web-app-rollingupdate-strategy
  labels:
    name: web-app-rollingupdate-strategy
    version: nanoserver-1709
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: web-app-rollingupdate-strategy
    version: nanoserver-1709
  type: LoadBalancer
