apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: web-app-rolling-update-strategy
  replicas: 3
  template:
    metadata:
      labels:
        app: web-app-rolling-update-strategy
    spec:
      containers:
        - name: web-app-rolling-update-strategy
          image: akhil90s/spring-boot-docker-project:1
