apiVersion: v1
kind: Service
metadata:
  name: recreate-strategy-service
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 8080
      nodePort: 30080
  type: NodePort
